### PR TITLE
Build configuration for external contributors

### PR DESCRIPTION
**Pull request by GianniCarlo**
This PR was inspired by @JanX2 and [his branch](https://github.com/JanX2/BookPlayer/tree/external-dev-setup) he shared with us via Discord (sorry it took me a while to get this done)

This introduces `.xcconfig` files, to make life easier for anyone running BookPlayer locally, there are two new files:
- Debug.template.xcconfig
- Release.xcconfig

which have the following parameters:
- `DEVELOPMENT_TEAM` → this is the id of your account
- `BP_ENTITLEMENTS` → BookPlayer supports CarPlay, but for debug purposes I've included a file that doesn't include those entitlements, the Debug template comes with this value filled in (BookPlayer-NoCarPlay)
- `BP_BUNDLE_IDENTIFIER` → your bundle identifier
- `BP_PROVISIONING_MAIN` → provisioning profile used for the app target
- `BP_PROVISIONING_WIDGET` → provisioning profile used for the old widget target
- `BP_PROVISIONING_WATCH` → provisioning profile used for the watch app
- `BP_PROVISIONING_WATCH_EXTENSION` → provisioning profile used for the watch app extension
- `BP_PROVISIONING_INTENTS` → provisioning profile used for siri intents (this can be a wildcard)
- `BP_PROVISIONING_WIDGET_UI` → provisioning profile used for the new widget target

I'll be updating the developer guide in our wiki before merging, but I can leave here some quick instructions for those running on simulators:
- First, make a copy of `Debug.template.xcconfig` and name it `Debug.xcconfig` in the same folder. 
- You can leave all the provisioning parameters blank, and just fill the `BP_BUNDLE_IDENTIFIER` and `BP_ENTITLEMENTS` parameters, it won't matter since for the simulator it's not necessary to code sign

If you're running on a device, then you'll have to create a lot of things in the [Apple developer website](https://developer.apple.com), starting with the section Identifiers (1 app groups, 1 icloud container, 5-6 app identifiers), but I'll update the guide later tomorrow

### CODE REVIEW

**Comment by GianniCarlo** [comment]
I have updated the Wiki with the proper steps, check it out → https://github.com/TortugaPower/BookPlayer/wiki/Developer-Guide#setting-up-the-project

**Comment by JanX2** [comment]
@GianniCarlo Awesome!

**Comment by Aishanur** [comment]
Hello, 
I was trying to run Book Player on my device, but I run into a couple of issues, specifically with iCloud and the share extension? I also noticed that the xcconfig file has changed a bit (I pasted the fields shown to me below). Is there anything extra that I have to do? 
Thank you

DEVELOPMENT_TEAM =
BP_ENTITLEMENTS = BookPlayer-NoCarPlay
BP_BUNDLE_IDENTIFIER = com.replace.me
BP_PROVISIONING_MAIN =
BP_PROVISIONING_WATCH =
BP_PROVISIONING_WATCH_EXTENSION =
BP_PROVISIONING_INTENTS =
BP_PROVISIONING_WIDGET_UI =
BP_PROVISIONING_SHARE_EXTENSION =
BP_SENTRY_DSN = replace.me
BP_REVENUECAT_KEY = replace.me
BP_MOCKED_BEARER_TOKEN = simulator.only
BP_IS_SOCKET_SECURE = false
BP_SOCKET_SERVER =
BP_API_SCHEME = http
BP_API_DOMAIN = replace.me
BP_API_PORT =

**Comment by GianniCarlo** [comment]
Hi @Aishanur , hmmmm can you bring this up over on Discord [#dev channel](https://discord.gg/s6gkMW8g), and provide some screenshots on the errors you're seeing?

**Pull request merged**
