### PR TITLE
Release 3.3.0

### PR DESCRIPTION
**Pull request by GianniCarlo**
We are finally done with v3.3.0 development 🎉

Rough notes on what is included in this version.

# Introducing: BookPlayer Plus

Support BookPlayer development and unlock more design options

- Colorful App Icon alternatives
- Additional color themes
- More extras will be added to future releases without the need for additional purchases.

BookPlayer will remain free and the free version will retain all features forever. We believe in Open Source and in free software. We also hope you enjoy it as much as we do and consider a donation to keep the lights on.

# New features & Improvements
* Dark Mode
* Bulk edit the items in your library and playlists
* New layout and interaction for skip controls in the player
* 3D Touch Quick Actions for fast access to the most recent book
* Completion of a book is now tracked independently from a book’s progress
* More options are available by swiping left on a cell in both Library and Playlists
* Optional creation of a new Playlist when importing books while inside a playlist
* Stop at chapter boundaries when skipping
* Tip Jar

# Bugfixes
* Fixed a cancelled on-chapter-end sleep timer
* Fixed the layout of the book title and the author Miniplayer layout title issues
* Accessibility improvements inside the player interface

### CODE REVIEW

**Comment by GianniCarlo** [comment]
I'll be uploading a version later today for TestFlight. If everything goes well throughout this week, we'll be launching the new version by the end of this week

**Comment by pichfl** [comment]
I updated your draft for the release notes above, please double check for spelling errors.

**Comment by GianniCarlo** [comment]
Thanks Florian 😁

**Comment by GianniCarlo** [comment]
and we're live on the App Store!

ps. once travis has support for swift 5 I'll push a change

**Pull request merged**
