### PR TITLE
Fix siri start

### PR DESCRIPTION
**Pull request by gpambrozio**
When using the Siri intent AND the app is not in the background when the app starts it plays from the beginning of the previous book but not form where you played last.

This creates a better flag to check if the book should start playing or if it should postpone.

### CODE REVIEW

**Comment by GianniCarlo** [comment]
hey @gpambrozio ! sorry for the delayed response, could you point this PR to the branch `develop`?, I'll be able to take a look this weekend I think, I'll have more comments then. Thanks for your contribution 😁

**Comment by gpambrozio** [comment]
@GianniCarlo done

**Comment by GianniCarlo** [comment]
@gpambrozio there's a conflict on the `AppDelegate` file. Other than that, I agree on the change from  `PlayerManager.shared.play()` to `self.playLastBook()`, but I still can't reproduce the issue you're mentioning. Does the app have to be closed from the multitask view?

**Comment by gpambrozio** [comment]
@GianniCarlo No more conflicts. 

To reproduce: Open the app, start a book and go to the middle. Stop, background then force quit the app using the multitask view.

Now ask siri to start the last book. It should start from the beginning, not where you left off.

**Comment by GianniCarlo** [comment]
I can't seem to reproduce it, but if it's forced quit, then the shortcut won't trigger the func `application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?)`, instead, the OS will add parameters to the options variable in `didFinishLaunchingWithOptions`. Look for this block that handles that in the `AppDelegate`:
```swift
if let activityDictionary = launchOptions?[.userActivityDictionary] as? [UIApplication.LaunchOptionsKey: Any],
            let activityType = activityDictionary[.userActivityType] as? String,
            activityType == Constants.UserActivityPlayback {
            defaults.set(true, forKey: activityType)// you can comment this out and test that the book won't start
        }
```
and that boolean is properly handled later inside the `LibraryViewController` func `loadLastBook`. Maybe the bug is somewhere else or I'm missing something 🤔

**Comment by GianniCarlo** [comment]
closing this due to inactivity, feel free to reopen when you get the chance 👍

**Comment by gpambrozio** [comment]
@GianniCarlo I'll open a new PR for this but it's weird you cannot reproduce it. I just checked and in the develop branch it still happens for me.

**Pull request closed without merging**
