### PR TITLE
Watch app support v1

### PR DESCRIPTION
**Pull request by GianniCarlo**
Finally watch support is coming.

This V1 will only act as a remote control for the main app. We'll leave for V2, things like syncing files and reproducing audio w/o the need of the phone being near.

The app consists of two pages:
- On the first page, you can navigate through your library and playlists, and see your last played book on top.
IMG_3975

- On the second page, we use the baked-in [Now Playing View](https://developer.apple.com/documentation/watchkit/adding_a_now_playing_view) which will show whatever was last played by the phone (it could be other apps, hence the need for the last-played-book on the library)
IMG_3974

Each time the app (phone) is launched, the application context is updated and the library information is synced to the watch. We also provide a menu (accessed by 3d-touch) on the watch with the option to manually request the phone to sync the library information. This could be improved, so no manual intervention is needed, but I think it will be best revisited for v2
IMG_3977

Things left to do:
- [x] Add empty screen state for the library
- [x] Add complication images

### CODE REVIEW

**Comment by GianniCarlo** [comment]
The now-playing-view is buggy. At first launch it'll show the information correctly, but after some time, it's presented like this (shifted downwards) and then it won't work
IMG_4020

The only option left, is to build a custom player view and not rely on Apple's component

**Comment by pichfl** [comment]
Whelp, only a zillion assets left to create 😅

**Comment by GianniCarlo** [comment]
We got around Apple's bug using [reloadRootPageControllers](https://developer.apple.com/documentation/watchkit/wkinterfacecontroller/2868441-reloadrootpagecontrollerswithnam?language=objc) on each selection. It's not ideal in the long run, and it will be replaced with a custom player for v2

**Comment by davidlist** [comment]
Hi, whats the status of v2? I think no other app provides this functionality and was the reason I discovered this project. Please let me know in case I can help! I am not a developer but I could help with testing or localization to German...

**Comment by d1rewolf** [comment]
Agreed...this app would be perfect if it could sync files and play them on the watch without the phone...

**Comment by GianniCarlo** [comment]
I'm currently focused on #287 , but if anyone in the community wants to contribute, please feel free to 😊 it'd be a huge help

**Comment by davidlist** [comment]
I think there is still no other app to offer that functionality and that’s what brought me here. I would be willing to put time an effort into this however I am not a developer and my programming experience is very little. However if someone would want to take the lead and start with the basic constrict i would try to help es much as possible.

**Pull request merged**
