### PR TITLE
Sort by most recent

### PR DESCRIPTION
**Pull request by huynhxloi**
Added ability to sort by most recent.

### CODE REVIEW

**Comment by GianniCarlo** [comment]
The project doesn't compile on my computer :/. I'm seeing some changes made to the `BookPlayer.xcodeproj/project.pbxproj` project file, which seems to be the reason TravisCI also is giving an error. It looks all related to the dependencies, I would suggest the following:
1.- Discard the changes made to the file `project.pbxproj`
2.- Run in your terminal the command `carthage bootstrap --platform ios` to setup the dependencies

Let me know if I can be of further help 👍

**Comment by huynhxloi** [comment]
I did a fetch then checkout the `project.pbxproj` from the masters and ran that carthage command but there's still a lot of buildtime errors.

image

**Comment by GianniCarlo** [comment]
We coud schedule a call to help you setup the environment 🤔. But yeah, it should work with carthage, also, there's a `;` semicolon missing in the new keys in the localized strings

**Comment by huynhxloi** [comment]
Missing semicolon fixed.

A call would be very helpful. Do you have Microsoft Teams? If not, Zoom?

**Comment by GianniCarlo** [comment]
we can do it via zoom @huynhxloi 👌, currently weekends (mornings and afternoons) work for me, my timezone is GMT-5

**Comment by GianniCarlo** [comment]
closing in favor of #475

**Pull request closed without merging**
